title: Dumb Test
author: Someone
email: someone@nowhere.com
description: Something
github_username: devnull00xx

markdown: kramdown

#remote_theme: pages-themes/modernist@v0.2.0
#theme: modernist
#plugins:
#  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

theme: jekyll-theme-minimal