title: Dumb Test
author: Someone
email: someone@nowhere.com
description: Something
github_username: devnull00xx

markdown: kramdown

plugins:
  - jekyll-remote-theme

#theme: minima

#theme: jekyll-theme-minimal

#remote_theme: pages-themes/modernist@v0.2.0
theme: jekyll-theme-time-machine

#remote_theme: pages-themes/cayman@v0.2.0
#theme: jekyll-theme-cayman

#remote_theme: pages-themes/architect@v0.2.0
#theme: jekyll-theme-architect
