title: Dumb Test
author: Someone
email: someone@nowhere.com
description: This is merely a dumb test
github_username: devnull00xx

markdown: kramdown

plugins:
  - jekyll-remote-theme

theme: jekyll-theme-time-machine
