title: Dumb Test
author: Someone
email: someone@nowhere.com
description: Something
github_username: devnull00xx

markdown: kramdown

plugins:
  - jekyll-remote-theme

#theme: jekyll-theme-time-machine
theme: jekyll-theme-modernist
#theme: jekyll-theme-cayman
#theme: jekyll-theme-architect
